# Generated by Django 4.2.7 on 2023-11-25 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_product_tags_product_vendor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("delivered", "Delivered"),
                    ("shipped", "Shipped"),
                    ("process", "Processing"),
                ],
                default="processing",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category",
                to="core.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("in_review", "In Review"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                    ("draft", "Draft"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "★⭒☆☆☆"),
                    (5, "★★★★★"),
                    (3, "★★★☆☆"),
                    (4, "★★★★☆"),
                    (2, "★★☆☆☆"),
                ],
                default=None,
            ),
        ),
    ]
