# Generated by Django 4.2.7 on 2023-11-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_product_life_product_mfd_product_stock_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("delivered", "Delivered"),
                    ("shipped", "Shipped"),
                    ("process", "Processing"),
                ],
                default="processing",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="life",
            field=models.CharField(
                blank=True, default="100 Days", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("rejected", "Rejected"),
                    ("in_review", "In Review"),
                    ("disabled", "Disabled"),
                    ("published", "Published"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                blank=True, default="Organic", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (2, "★★☆☆☆"),
                    (5, "★★★★★"),
                    (1, "★⭒☆☆☆"),
                    (4, "★★★★☆"),
                    (3, "★★★☆☆"),
                ],
                default=None,
            ),
        ),
    ]
