# Generated by Django 4.2.7 on 2023-11-26 04:04

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("core", "0009_alter_cartorder_product_status_alter_product_life_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("disabled", "Disabled"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                    ("in_review", "In Review"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (4, "★★★★☆"),
                    (5, "★★★★★"),
                    (1, "★⭒☆☆☆"),
                    (2, "★★☆☆☆"),
                    (3, "★★★☆☆"),
                ],
                default=None,
            ),
        ),
    ]
