# Generated by Django 4.2.7 on 2023-12-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_cartorder_product_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="mobile",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (3, "★★★☆☆"),
                    (2, "★★☆☆☆"),
                    (4, "★★★★☆"),
                    (1, "★☆☆☆☆"),
                    (5, "★★★★★"),
                ],
                default=None,
            ),
        ),
    ]
