# Generated by Django 4.2.7 on 2023-12-06 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0013_address_mobile_alter_productreview_rating"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="wishlist",
            new_name="wishlist_model",
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("delivered", "Delivered"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                ],
                default="processing",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("rejected", "Rejected"),
                    ("draft", "Draft"),
                    ("in_review", "In Review"),
                    ("disabled", "Disabled"),
                    ("published", "Published"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (5, "★★★★★"),
                    (4, "★★★★☆"),
                    (3, "★★★☆☆"),
                    (2, "★★☆☆☆"),
                    (1, "★☆☆☆☆"),
                ],
                default=None,
            ),
        ),
    ]
