# Generated by Django 4.2.7 on 2023-12-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_rename_wishlist_wishlist_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="order_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("disabled", "Disabled"),
                    ("in_review", "In Review"),
                    ("rejected", "Rejected"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (4, "★★★★☆"),
                    (1, "★☆☆☆☆"),
                    (5, "★★★★★"),
                    (2, "★★☆☆☆"),
                    (3, "★★★☆☆"),
                ],
                default=None,
            ),
        ),
    ]
