# Generated by Django 4.2.7 on 2023-12-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_remove_vendor_rating12_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="rating_vendor",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("delivered", "Delivered"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                ],
                default="processing",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("draft", "Draft"),
                    ("in_review", "In Review"),
                    ("rejected", "Rejected"),
                    ("disabled", "Disabled"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (2, "★★☆☆☆"),
                    (3, "★★★☆☆"),
                    (4, "★★★★☆"),
                    (5, "★★★★★"),
                    (1, "★☆☆☆☆"),
                ],
                default=None,
            ),
        ),
    ]
